GET http://localhost:5000/foo
####
GET http://localhost:5000/bar
###
GET http://localhost:5000/product-to-json
###
GET http://localhost:5000/json-to-product
###
GET http://localhost:5000/products
###
POST http://localhost:5000/products

{
    "productId": 0,
    "manufacturer": "New Company",
    "sku": "01",
    "upc": "02",
    "pricePerUnit": "25.00",
    "quantityOnHand": 5,
    "productName": "Lego"
}
### undefined method
OPTIONS  http://localhost:5000/products
### get product 1
GET  http://localhost:5000/products/1
### get product 2
GET  http://localhost:5000/products/2
### get product 3
GET  http://localhost:5000/products/3
### update product 3
PUT  http://localhost:5000/products/3

{
    "productId": 3,
    "manufacturer": "Company Updated",
    "sku": "0000",
    "upc": "1111",
    "pricePerUnit": "50.00",
    "quantityOnHand": 50,
    "productName": "Pizza"
}
